[package]
name = "all_colors"
version = "0.0.1"
edition = "2021"
authors = ["Timothy Jay <TimothyRJay@gmail.com>"]

[dependencies]
bmp = "0.5.0"
rand = "0.8.5"
rayon = "1.7.0"
chrono = "0.4.24"
rustc-hash = "1.1.0"
num = "0.4.0"
thiserror = "1.0.40"
lazy_static = "1.4.0"
base64 = "0.21.2"